#!/bin/sh
#
# Start startx
#
BIN=/usr/bin/startx
PIDFILE=/var/run/startx.pid

DISPLAY=:0.0                                                                                                                                                          
USER=root                                                                                                                                                             
HOME=/root                                                                                                                                                            
                                                                                                                                                                      
export DISPLAY                                                                                                                                                        
export USER                                                                                                                                                           
export HOME

start() {
        printf "Starting startx: "
	start-stop-daemon -S -q -b -m -p $PIDFILE --user $USER --exec $BIN
        [ $? = 0 ] && sleep 1 && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping startx: "
        start-stop-daemon -K -q -p $PIDFILE
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
        stop
        sleep 2
        start
}

case "$1" in
        start)
                start
        ;;
        stop)
                stop
        ;;
        restart|reload)
                restart
        ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
